Repository librecores/docker-images, pull requests merged in 2019-07, with the labels that each got.

#20 Create a LibreCores CI Image for OpenRISC, RISC V Image now inherits the main LibreCores CI one
  librecores-ci-openrisc/Dockerfile
  librecores-ci-riscv/Dockerfile
Labels: enhancement

#23 Add README stub for the OpenRISC image
  librecores-ci-openrisc/README.md
Labels: skip-changelog

#25 Updating librecores-ci-openrisc to remove cores required by or1k-tests
  librecores-ci-openrisc/Dockerfile
Labels: skip-changelog

#26 Add documentation for librecores-ci-openrisc docker image
  librecores-ci-openrisc/README.md
Labels: documentation
